services:
  mspr2-mosquitto:
    image: eclipse-mosquitto:2
    container_name: mspr2-mosquitto
    restart: unless-stopped
    ports:
      - "${MQTT_PORT:-1883}:1883"   # MQTT
      - "${MQTT_WEBSOCKET_PORT:-9001}:9001"   # websockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mspr2-influxdb-live:
    image: influxdb:2
    container_name: mspr2-influxdb-live
    restart: unless-stopped
    ports:
      - "${INFLUXDB_LIVE_PORT:-8086}:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME:-admin}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD:-adminadmin}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_LIVE_ORG:-iot}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET_LIVE:-sensor_live}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_LIVE_TOKEN:-iot-live-token}
    volumes:
      - influxdb_live_data_mspr2:/var/lib/influxdb2
      - influxdb_live_config_mspr2:/etc/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  mspr2-influxdb-staging:
    image: influxdb:2
    container_name: mspr2-influxdb-staging
    restart: unless-stopped
    ports:
      - "${INFLUXDB_STAGING_PORT:-8087}:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME:-admin}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD:-adminadmin}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_STAGING_ORG:-iot}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET_STAGING:-sensor_staging}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_STAGING_TOKEN:-iot-staging-token}
    volumes:
      - influxdb_staging_data_mspr2:/var/lib/influxdb2
      - influxdb_staging_config_mspr2:/etc/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  mspr2-telegraf:
    image: telegraf:1.32
    container_name: mspr2-telegraf
    restart: unless-stopped
    depends_on:
      mspr2-mosquitto:
        condition: service_started
      mspr2-influxdb-staging:
        condition: service_healthy
    environment:
      INFLUXDB_STAGING_TOKEN: ${INFLUXDB_STAGING_TOKEN:-iot-staging-token}
      INFLUXDB_STAGING_ORG: ${INFLUXDB_STAGING_ORG:-iot}
      INFLUXDB_BUCKET_STAGING: ${INFLUXDB_BUCKET_STAGING:-sensor_staging}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro


  mspr2-postgres:
    image: postgres:18
    container_name: mspr2-postgres_business_mspr
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_business_app_mspr2:/var/lib/postgresql
      - ./datas/gold:/datas/gold:ro
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  mspr2-flyway-business-postgres:
    container_name: mspr2-flyway-business-postgres
    image: flyway/flyway
    volumes:
      - ./bdd/migrations:/flyway/sql
    depends_on:
      mspr2-postgres:
        condition: service_healthy       # ← attend le healthcheck, pas juste le démarrage
    command: >
      -url=jdbc:postgresql://mspr2-postgres:5432/${POSTGRES_DB}
      -schemas=public
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      migrate
  

volumes:
  postgres_business_app_mspr2:
  influxdb_live_data_mspr2:
  influxdb_live_config_mspr2:
  influxdb_staging_data_mspr2:
  influxdb_staging_config_mspr2: