services:

  influxdb3-ui-a:
    image: influxdata/influxdb3-ui:1.9.0
    container_name: mspr2-influxdb3-explorer_a
    ports:
      - "${INFLUXDBUI_IP_HOST:-127.0.0.1}:${INFLUXDBUI_A_WEBUI_PORT:-8888}:8080"
    volumes:
      - influxdb3-ui-db_a_mspr2:/db
    restart: unless-stopped

  influxdb3-ui-b:
    image: influxdata/influxdb3-ui:1.9.0
    container_name: mspr2-influxdb3-explorer_b
    ports:
      - "${INFLUXDBUI_IP_HOST:-127.0.0.1}:${INFLUXDBUI_B_WEBUI_PORT:-8888}:8080"
    volumes:
      - influxdb3-ui-db_b_mspr2:/db
    restart: unless-stopped

volumes:
  influxdb3-ui-db_a_mspr2:
  influxdb3-ui-db_b_mspr2: